os: osx
osx_image: xcode10.2

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - "node_modules"

before_script:
  - curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.33.0/ktlint
  - chmod a+x ktlint
  - swiftlint version

script:
  - npm run lint
  - ./ktlint --color src/android/*
