on: push
name: Security
jobs:
  runaSecurityAudit:
    name: Run a security audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run a security audit
      uses: actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437
      with:
        entrypoint: npm
        args: audit
